### ISSUE TITLE
Learn How to Use Zenhub

### ISSUE THREAD

**Issue by ambear-g** [John9670/Attend-In#10]
- how to give rights to everyone
- other things zen hub can do
- is there a way to view a main board???
- how to make sprints (a way to label when things are done maybe?)

**Comment by vpatel04** [comment]
I watched some videos on ZenHub tutorials. I recommend we create epic for the issues that can be solved within 2-3sprints.
It will all take us some more time to get use to ZenHub since we all are new here. I am positing a link of the video I found useful. 

https://www.youtube.com/watch?v=tJ375ju3xTc
https://www.youtube.com/watch?v=dMG_-551xV4
