### ISSUE TITLE
Finalized App Logo

### ISSUE THREAD

**Issue by John9670** [John9670/Attend-In#47]

**Comment by Jpopo** [comment]
[Apple_Stem.pdf](https://github.com/John9670/Attend-In/files/6145290/Apple_Stem.pdf)
[Apple_Leaf.pdf](https://github.com/John9670/Attend-In/files/6145294/Apple_Leaf.pdf)
[Pencil_GPS.pdf](https://github.com/John9670/Attend-In/files/6145295/Pencil_GPS.pdf)

These are the PDF version since Github does not allow you to attach the PSD files.

**Comment by Jpopo** [comment]
![image0](https://user-images.githubusercontent.com/47196827/111239488-a7827000-85cf-11eb-913a-897bdfcf0207.png)
These were the initial suggestions / sketches
